services:
  php:
    container_name: php
    profiles:
    - backend
    - all
    - php
    image: ${PROJECT_NAME}-${CONFIG_SYSTEM}-mono-${CONFIG_MONOLITHIC}-${CONFIG_MONOLITHIC_VERSION}-php-${VERSION}:latest
    build: .
    volumes:
      - ${PROJECT_PATH}/monolithic/${CONFIG_MONOLITHIC}/${CONFIG_MONOLITHIC_VERSION}:/var/www/html:consistent
      - ${PROJECT_PATH}/monolithic/${CONFIG_MONOLITHIC}/${CONFIG_MONOLITHIC_VERSION}/var/xdebug:/tmp/xdebug
    networks:
      - proxy
      - host_network
    #tty need for error log to standard error
    tty: true
    #command: /bin/bash
    
