services:
  laravel-nginx:
    container_name: laravel-nginx
    profiles:
      - backend
      - all
      - laravel-nginx
    image: ${PROJECT_NAME}-${CONFIG_SYSTEM}-micro-${CONFIG_BACKEND}-${CONFIG_BACKEND_VERSION}-laravel-nginx-${VERSION}:latest
    build: .
    env_file:
      - ${PROJECT_PATH}/docker/.env
    environment:
      - DOMAIN=${DOMAIN}  
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      #multi tenant
      #- "traefik.http.routers.laravel-nginx.rule=HostRegexp(`([a-z0-9-]+\\.)?laravel-multi-template\\.localhost`)"
      - traefik.http.routers.laravel-nginx.rule=Host(`laravel-${DOMAIN}`)
      - "traefik.http.routers.laravel-nginx.tls=${DOCKER_STACK_SSL}"
      - "traefik.http.services.laravel-nginx.loadbalancer.server.port=80"
    volumes:
      - ${PROJECT_PATH}/backend/${CONFIG_BACKEND}/${CONFIG_BACKEND_VERSION}:/var/www/html:consistent
    networks:
      - proxy
      - host_network
    #tty need for error log to standard error
    tty: true
    #command: /bin/bash