services:
  nginx:
    container_name: nginx
    profiles:
    - backend
    - all
    - nginx
    image: ${PROJECT_NAME}-${CONFIG_SYSTEM}-mono-${CONFIG_MONOLITHIC}-${CONFIG_MONOLITHIC_VERSION}-nginx-${VERSION}:latest
    build: .
    env_file:
      - ${PROJECT_PATH}/docker/.env
    environment:
      - DOMAIN=${DOMAIN}  
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.backend.tls=${DOCKER_STACK_SSL}
      - traefik.http.services.backend.loadbalancer.server.port=80
    volumes:
      - ${PROJECT_PATH}/monolithic/${CONFIG_MONOLITHIC}/${CONFIG_MONOLITHIC_VERSION}:/var/www/html:consistent
    networks:
      - proxy
      - host_network
    #tty need for error log to standard error
    tty: true
    #command: /bin/bash

