services:
  nestjs-be-nginx:
    container_name: nestjs-be-nginx
    profiles:
      - backend
      - all
      - nestjs-be-nginx
    image: ${PROJECT_NAME}-${CONFIG_SYSTEM}-micro-${CONFIG_BACKEND}-${CONFIG_BACKEND_VERSION}-nestjs-be-nginx-${VERSION}:latest
    build: .
    env_file:
      - ${PROJECT_PATH}/docker/.env
    environment:
      - DOMAIN=${DOMAIN}  
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nestjs-be-nginx.rule=Host(`nestjs-be-${DOMAIN}`)"
      - "traefik.http.routers.nestjs-be-nginx.tls=${DOCKER_STACK_SSL}"
      - "traefik.http.services.nestjs-be-nginx.loadbalancer.server.port=80"
    volumes:
      - ${PROJECT_PATH}/backend/${CONFIG_BACKEND}/${CONFIG_BACKEND_VERSION}:/var/www/html:consistent
    networks:
      - proxy
      - host_network
    #tty need for error log to standard error
    tty: true
    #command: /bin/bash