
services:
  node:
    container_name: node
    profiles:
    - tools
    - all
    - node
    image: ${PROJECT_NAME}-${CONFIG_SYSTEM}-micro-${CONFIG_FRONTEND}-${CONFIG_FRONTEND_VERSION}-node-${VERSION}:latest
    build: .
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.node.rule=Host(`node-${DOMAIN}`)
      - traefik.http.routers.node.tls=${DOCKER_STACK_SSL}
      - traefik.http.services.node.loadbalancer.server.port=80
    volumes:
      - ${PROJECT_PATH}/frontend/${CONFIG_FRONTEND}/${CONFIG_FRONTEND_VERSION}:/var/www/html:consistent
    environment:
      NODE_ENV: development
    tty: true
    #command: /bin/bash
    command: npm run --prefix /var/www/html dev
    networks:
      - proxy
      - host_network
  