services:
  clickhouse:
    container_name: clickhouse
    profiles:
    - backend
    - all
    - clickhouse
    image: ${PROJECT_NAME}-${CONFIG_SYSTEM}-${CONFIG_MONOLITHIC}-${CONFIG_MONOLITHIC_VERSION}-clickhouse-${VERSION}:latest
    build: ../../../../../tools/database/clickhouse
    restart: no
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    ports:
      - 18123:8123
      - 8000:9000
    environment:
      CLICKHOUSE_USER: ${PROJECT_NAME}
      CLICKHOUSE_PASSWORD: ${PROJECT_NAME}
      TZ: UTC
    #tty: true
    #command: /bin/bash
    volumes:
      - ${PROJECT_NAME}-${CONFIG_SYSTEM}-mono-${CONFIG_MONOLITHIC}-${CONFIG_MONOLITHIC_VERSION}-clickhouse-db:/var/lib/clickhouse
      - ${PROJECT_NAME}-${CONFIG_SYSTEM}-mono-${CONFIG_MONOLITHIC}-${CONFIG_MONOLITHIC_VERSION}-clickhouse-log:/var/log/clickhouse-server
      # - ./config/config.xml:/etc/clickhouse-server/config.xml
      # - ./config/users.xml:/etc/clickhouse-server/users.xml

    networks:
      - proxy
      - host_network