
services:
  laravel-node:
    container_name: laravel-node
    profiles:
    - tools
    - all
    - laravel-node
    image: ${PROJECT_NAME}-${CONFIG_SYSTEM}-micro-${CONFIG_BACKEND}-${CONFIG_BACKEND_VERSION}-laravel-node-${VERSION}:latest
    build: .
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.laravel-node.rule=Host(`laravel-node-${DOMAIN}`)
      - traefik.http.routers.laravel-node.tls=${DOCKER_STACK_SSL}
      - traefik.http.services.laravel-node.loadbalancer.server.port=80
    volumes:
      - ${PROJECT_PATH}/backend/${CONFIG_BACKEND}/${CONFIG_BACKEND_VERSION}:/var/www/html:consistent
    environment:
      NODE_ENV: development
    tty: true
    #command: /bin/bash
    command: npm run dev
    #command: npm run --prefix /var/www/html dev
    networks:
      - proxy
      - host_network
  