
services:
  react-node:
    container_name: react-node
    profiles:
    - tools
    - all
    - react-node
    image: ${PROJECT_NAME}-${CONFIG_SYSTEM}-micro-${CONFIG_FRONTEND}-${CONFIG_FRONTEND_VERSION}-react-node-${VERSION}:latest
    build: .
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.react-node.rule=Host(`react-node-${DOMAIN}`)
      - traefik.http.routers.react-node.tls=${DOCKER_STACK_SSL}
      - traefik.http.services.react-node.loadbalancer.server.port=80
    volumes:
      - ${PROJECT_PATH}/frontend/${CONFIG_FRONTEND}/${CONFIG_FRONTEND_VERSION}:/var/www/html:consistent
    environment:
      NODE_ENV: development
    tty: true
    #command: /bin/bash
    command: npm run dev
    networks:
      - proxy
      - host_network
  